POST http://localhost:3200/product
Content-Type: application/json
Accept: application/json

{
  "name": "fiber"
}

###
GET http://localhost:3200/product/123s
Accept: application/json

###
GET http://localhost:3200/product/123s/fiber
Accept: application/json

###
PUT http://localhost:3200/product/123s
Content-Type: application/json
Accept: application/json

{
"name": "fiber"
}

###
DELETE http://localhost:3200/product/123s
Accept: application/json