POST http://localhost:3200/api/v1/product
Content-Type: application/json
Accept: application/json

{
  "name": "fiber"
}

###
GET http://localhost:3200/api/v1/product
Accept: application/json

###
GET http://localhost:3200/api/v1/product/123s
Accept: application/json

###
GET http://localhost:3200/product/123s/fiber
Accept: application/json

###
PUT http://localhost:3200/product/123s
Content-Type: application/json
Accept: application/json

{
"name": "fiber"
}

###
DELETE http://localhost:3200/api/v1/product/62e7f140c4d44f437aeb552b
Accept: application/json